[package]
name = "lithophoto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
clap = "2.33.0"
indicatif = "0.16.2"